import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import ProfilePic from "../../public/images/profile/pic1.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
// import lightBulb from "../../public/images/svgs/miscellaneou_icons_1.svg"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <TransitionEffect/> */}
      <main className='flex items-center w-full min-h-screen dark:text-primary'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/2 md:w-full'>
              <Image src={ProfilePic} alt="pic1" className='w-full h-auto lg:hidden md:inline-block md:w-full'
              priority 
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw" />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Turning Vision Into Reality With Code And Design." className='text-5xl !text-left
              lx:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' />
              <p className='my-2 text-base font-medium md:text-sm sm:text-xs'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/dummy.pdf" target={'_blank'}
                className='flex items-center bg-dark text-white p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-white hover:text-black border-2 border-solid border-transparent
                hover:border-dark dark:bg-primary dark:hover:text-white dark:text-dark dark:hover:border-white
                
                md:p-2 md:px-4 md:text-base'
                >
                Resume <LinkArrow/>
                </Link>
                <Link href="/countact" traget={'_blank'}
                className='ml-4 text-lg font-medium text-dark dark:text-white capitalize hover:underline md:text-base'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        
      </main>
    </>
  )
}
